import{a as S,S as P,i as f}from"./assets/vendor-BDaiwwc1.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const B="47415384-99a3119bdb6a092e7cf8e4330",M="https://pixabay.com/api/";async function g(t,n=1,o=15){const s=`${M}?key=${B}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${n}&per_page=${o}`;try{return(await S.get(s)).data}catch(e){throw console.error("Fetch Images Error:",e.message),e}}const d=document.createElement("div");d.classList.add("gallery");document.body.appendChild(d);const a=document.createElement("div");a.classList.add("loader");a.style.display="none";a.innerHTML='<div class="css-loader"></div>';document.body.appendChild(a);const h=document.createElement("form");h.id="search-form";h.innerHTML=`
  <input type="text" id="search-input" placeholder="Search images...">
  <button type="submit">Search</button>
`;document.body.prepend(h);const H=new P(".gallery a");function I(){d.innerHTML=""}function b(){a.style.display="block"}function l(){a.style.display="none"}function L(t){const n=t.map(({webformatURL:o,largeImageURL:s,tags:e,likes:r,views:i,comments:v,downloads:$})=>`
        <a href="${s}">
          <img src="${o}" alt="${e}">
          <div>
            <p>Likes: ${r}</p>
            <p>Views: ${i}</p>
            <p>Comments: ${v}</p>
            <p>Downloads: ${$}</p>
          </div>
        </a>
      `).join("");d.insertAdjacentHTML("beforeend",n),H.refresh()}function u(t){f.error({title:"Error",message:t})}function w(t){f.warning({title:"No Results",message:t})}const q=document.getElementById("search-form"),C=document.getElementById("search-input"),y=document.querySelector(".load-more");let c=1,m="",p=0;q.addEventListener("submit",async t=>{t.preventDefault();const n=C.value.trim();if(!n){u("Search field cannot be empty!");return}m=n,c=1,I(),E(),b();try{const o=await g(c,m);if(p=o.totalHits,l(),!o.hits.length){w("Sorry, there are no images matching your search query. Please try again!");return}L(o.hits),o.hits.length<p&&O()}catch{l(),u("Something went wrong. Please try again later!")}});y.addEventListener("click",async()=>{c++,b();try{const t=await g(c,m);l(),L(t.hits),c*40>=p&&(E(),w("We're sorry, but you've reached the end of search results.")),x()}catch{l(),u("Something went wrong. Please try again later!")}});function O(){y.style.display="block"}function E(){y.style.display="none"}function x(){const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behaior:"smooth"})}
//# sourceMappingURL=index.js.map
