import{a as v,S as $,i as f}from"./assets/vendor-tnUJPedx.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const S="47415384-99a3119bdb6a092e7cf8e4330",C="https://pixabay.com/api/";async function h(t,r=1,n=15){const a=`${C}?key=${S}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${n}`;try{return(await v.get(a)).data}catch(e){throw console.error("Fetch Images Error:",e.message),e}}const y=document.createElement("div");y.classList.add("gallery");document.body.appendChild(y);const c=document.createElement("div");c.classList.add("loader");c.style.display="none";c.innerHTML='<div class="css-loader"></div>';document.body.appendChild(c);const P=new $(".gallery a");function I(){y.innerHTML=""}function g(){c.style.display="block"}function u(){c.style.display="none"}function b(t){const r=t.map(({webformatURL:n,largeImageURL:a,tags:e,likes:o,views:l,comments:L,downloads:E})=>`
        <a href="${a}">
          <img src="${n}" alt="${e}">
          <div>
            <p>Likes: ${o}</p>
            <p>Views: ${l}</p>
            <p>Comments: ${L}</p>
            <p>Downloads: ${E}</p>
          </div>
        </a>
      `).join("");y.insertAdjacentHTML("beforeend",r),P.refresh()}function p(t){f.error({title:"Error",message:t})}function O(t){f.warning({title:"No Results",message:t})}function w(){f.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results."})}const B=document.getElementById("search-form"),H=document.getElementById("search-input"),s=document.createElement("button");s.textContent="Load more";s.classList.add("load-more");s.style.display="none";document.body.appendChild(s);let d="",i=1,m=0;B.addEventListener("submit",async t=>{t.preventDefault();const r=H.value.trim();if(!r){p("Search field cannot be empty!");return}r!==d&&(d=r,i=1,I(),s.style.display="none"),g();try{const n=await h(d,i,15);if(u(),!n.hits.length){O("Sorry, there are no images matching your search query.");return}m=n.totalHits,b(n.hits),i*15>=m?(w(),s.style.display="none"):s.style.display="block"}catch{u(),p("Something went wrong. Please try again later!")}});s.addEventListener("click",async()=>{i+=1,g();try{const t=await h(d,i,15);u(),b(t.hits),i*15>=m&&(w(),s.style.display="none");const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}catch{u(),p("Something went wrong. Please try again later!")}});
//# sourceMappingURL=index.js.map
